### ISSUE TITLE
Multiple animations in animationName property

### ISSUE THREAD

**Issue by semanser** [FormidableLabs/radium#809] opened 2016-08-05 10:43 UTC
Hi. Is there any way to assign multiple values to `animationName`? 

For example I want something like this:

```
var animationOne = Radium.keyframes({
  '0%': {width: '10%'},
  '100%': {width: '100%'},
}, 'one');

var animationTwo = Radium.keyframes({
  '0%': {height: '10%'},
  '100%': {height: '100%'},
}, 'two');

var styles = {
  inner: {
    animation: 'x 3s ease 0s infinite',
    animationName: [animationOne, animationTwo], // how to do this?
  }
};
```

I need this because I want to implement [**chain animations**](http://stackoverflow.com/questions/7825509/css3-chain-animations).
How to realize this with Radium (or may be without)?

**Comment by ianobermiller** [comment] 2016-08-06 18:13
Ah cool, we should be able to support this. We should just look for an array in `animationName` and concat them together with `','`. I think you'd need to duplicate the other animation parameters as well:

```js
animation: 'x 3s ease 0s infinite, x 3s ease 0s infinite',
```

**Comment by alexlande** [comment] 2016-08-08 23:01
Duplicate of #675

**Closed by alexlande** 2016-08-08 23:01 UTC
Labels: enhancement

**Comment by wilsonsk** [comment] 2018-01-20 01:17
Was this ever addressed?
