### ISSUE TITLE
Cannot access ref in component when used with Radium

### ISSUE THREAD

**Issue by austincondiff** [FormidableLabs/radium#946] opened 2017-11-30 21:36 UTC
When I try to access a ref from a function in my component, it does not recognize it when the component is decorated with Radium. It refers to the component's this when the ref is being stored on the RadiumEnhancer. Any ideas on how I can access my ref?

**Comment by ryan-roemer** [comment] 2017-11-30 23:00
@acondiff -- Can you create a minimal repository that exposes the issue then include install + steps to reproduce the error? We can jump in and more easily diagnose things from there... Thanks!

**Comment by ryan-roemer** [comment] 2018-06-26 16:10
Closing due to lack of reproduction. If you're still experience the issue, please create a minimal public repository with install + error reproduction steps so we can clone it down and see what you're seeing directly and we'll re-open. Thanks!

**Closed by ryan-roemer** 2018-06-26 16:10 UTC
Labels: unverified
