### ISSUE TITLE
Hover style doesn't get removed when child element disappears

### ISSUE THREAD

**Issue by polkovnikov-ph** [FormidableLabs/radium#527] opened 2016-01-13 16:15 UTC
I have a dropdown button that shows popup menu when clicked. The `div` of popup menu is inside of the button, so when popup is hovered the `:hover` on a button is active. When menu gets closed via `display: none` being set via `onClick` handler, the button retains its style.

**Comment by ianobermiller** [comment] 2016-01-16 21:45
Yes, this is a known issue, and we don't really know the best way to solve it yet. Can you create a really [simple JSBin](https://github.com/FormidableLabs/radium/tree/master/docs/faq#how-can-i-use-radium-with-jsbin) so we can test possible solutions? Thanks!

**Comment by ianobermiller** [comment] 2016-01-16 21:54
Here is a simple example: https://jsbin.com/hexiwi/edit?js,output

**Comment by polkovnikov-ph** [comment] 2016-01-16 22:25
I've modified an example a bit: https://jsbin.com/wuvisiruta/1/edit?js,output

Steps to reproduce:
 1. Click "hello" word
 2. Click "close" word

**Comment by alex-wilmer** [comment] 2016-07-18 20:38
Anyone using a workaround for this problem at the moment? Not sure which direction to take it.

**Comment by alexlande** [comment] 2017-09-16 18:42
Closing this as a duplicate of #524

**Closed by alexlande** 2017-09-16 18:42 UTC
Labels: bug
