### ISSUE TITLE
0.15.2 fails postinstall on Windows

### ISSUE THREAD

**Issue by marudor** [FormidableLabs/radium#420] opened 2015-11-16 08:41 UTC
![error](http://s27.postimg.org/mevruelnn/2015_11_16_09_39_10_cmd_Admin.jpg)

Tried it several times just in case it is a permission Problem (I get that once in a while with windows...)

**Comment by pswai** [comment] 2015-11-16 12:15
This happens on Mac 10.11.1 (Node 5.0.0) too.

![screen shot 2015-11-16 at 8 13 11 pm](https://cloud.githubusercontent.com/assets/5335123/11181624/a9528e86-8c9e-11e5-8014-56a7151a6f31.png)

**Comment by ianobermiller** [comment] 2015-11-16 15:58
As the comment says, may you please provide npm-debug.log? The part you are both showing in the screenshot is not the actual error.

**Comment by marudor** [comment] 2015-11-16 16:08
The radium related bits:
https://gist.github.com/marudor/580a05b99668c9aa4340

**Comment by ryan-roemer** [comment] 2015-11-16 16:27
Random commment here -- in the case there is an issue with the `lib` detection in `postinstall` here:

```
"postinstall": "node -e \"require('fs').stat('lib', function(e,s){process.exit(e || !s.isDirectory() ? 1 : 0)})\" || npm run lib",
```

You may be able to switch to:

```
"postinstall": "cd lib || npm run lib",
```

In a portable way on Mac/Linux/Win (although I haven't tested win yet).

/ht @exogen for the suggestion

**Comment by ianobermiller** [comment] 2015-11-16 16:33
@ryan-roemer the `postinstall` script has been solid for a while, I am fairly certain this is due to removing .npmignore in favor of `files

**Comment by ianobermiller** [comment] 2015-11-16 16:59
Can someone please verify that 0.15.3 fixes the issue?

**Comment by exogen** [comment] 2015-11-16 18:37
I couldn't repro the error, but I did see that 0.15.2 needed to build lib on postinstall. I verified that 0.15.3 no longer does the build. But I think the issue does point out a problem with our `postinstall` method – if it throws an error when `lib` doesn't exist instead of building, then something's wrong.

**Comment by pswai** [comment] 2015-11-17 01:24
This is the debug log (renamed to .txt to attach it here) when I try to install 0.15.2 again.
Also, 0.15.3 installs properly.

[npm-debug.log.txt](https://github.com/FormidableLabs/radium/files/36137/npm-debug.log.txt)

**Comment by exogen** [comment] 2015-11-17 01:35
@pswai Thanks! Would you mind posting the output of a few commands here, to help debug? So far I haven't found any hints in npm-debug, but I have a hunch this is shell related. Try:

```sh
which sh
echo $SHELL
echo $SHELLOPTS
```

^ If we had the output of those, this might lead us to the cause.

**Comment by pswai** [comment] 2015-11-17 03:15
@exogen I am not in front of my Mac now, but I am still able to reproduce the issue with my Windows 10 machine. Here's the logs:

[Uploading npm-debug-radium.log.txt…](npm-debug.log for `npm install radium@0.15.2`)
[Uploading npm-debug-shell.log.txt…](npm-debug.log for `npm install npm-shell-debug`)

This is the output of running `npm install npm-sheel-debug`
```
PSWai@PSWai-PC MINGW64 ~/WebstormProjects/pandora (master)
$ npm install npm-shell-debug

> npm-shell-debug@1.0.3 postinstall C:\Users\PSWai\WebstormProjects\pandora\node_modules\npm-shell-debug
> npm run debug


> npm-shell-debug@1.0.3 debug C:\Users\PSWai\WebstormProjects\pandora\node_modules\npm-shell-debug
> which sh; echo $SHELL; echo $SHELLOPTS; shopt

which: no sh; in (/c/Program Files (x86)/nodejs/node_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/c/Program Files (x86)/nodejs/node
_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/mingw64/bin:/usr/bin:/c/Users/PSWai/bin:/c/ProgramData/Oracle/Java/javapath:/c/WINDOW
S/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Common Files/Roxio Shared/OEM/DLLShared:/c/Program Files (x86)/Co
mmon Files/Roxio Shared/OEM/12.0/DLLShared:/c/Program Files (x86)/Roxio/OEM/AudioCore:/c/Program Files/Perforce:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/Skype/Phone:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cmd:/
c/Program Files (x86)/nodejs:/c/Ruby200-x64/bin:/c/tools/php:/c/tools/arcanist/bin:/c/Python27:/c/mongodb/bin:/c/Users/PSWai/AppData/Roaming/npm)
/usr/bin/echo
which: no $SHELL; in (/c/Program Files (x86)/nodejs/node_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/c/Program Files (x86)/nodejs/
node_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/mingw64/bin:/usr/bin:/c/Users/PSWai/bin:/c/ProgramData/Oracle/Java/javapath:/c/WI
NDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Common Files/Roxio Shared/OEM/DLLShared:/c/Program Files (x86
)/Common Files/Roxio Shared/OEM/12.0/DLLShared:/c/Program Files (x86)/Roxio/OEM/AudioCore:/c/Program Files/Perforce:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/Skype/Phone:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c
md:/c/Program Files (x86)/nodejs:/c/Ruby200-x64/bin:/c/tools/php:/c/tools/arcanist/bin:/c/Python27:/c/mongodb/bin:/c/Users/PSWai/AppData/Roaming/npm)
/usr/bin/echo
which: no $SHELLOPTS; in (/c/Program Files (x86)/nodejs/node_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/c/Program Files (x86)/nod
ejs/node_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/mingw64/bin:/usr/bin:/c/Users/PSWai/bin:/c/ProgramData/Oracle/Java/javapath:/
c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Common Files/Roxio Shared/OEM/DLLShared:/c/Program Files
(x86)/Common Files/Roxio Shared/OEM/12.0/DLLShared:/c/Program Files (x86)/Roxio/OEM/AudioCore:/c/Program Files/Perforce:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/Skype/Phone:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Commo
n:/cmd:/c/Program Files (x86)/nodejs:/c/Ruby200-x64/bin:/c/tools/php:/c/tools/arcanist/bin:/c/Python27:/c/mongodb/bin:/c/Users/PSWai/AppData/Roaming/npm)
which: no shopt in (/c/Program Files (x86)/nodejs/node_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/c/Program Files (x86)/nodejs/no
de_modules/npm/bin/node-gyp-bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/npm-shell-debug/node_modules/.bin:/c/Users/PSWai/WebstormProjects/pandora/node_modules/.bin:/mingw64/bin:/usr/bin:/c/Users/PSWai/bin:/c/ProgramData/Oracle/Java/javapath:/c/WIND
OWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Common Files/Roxio Shared/OEM/DLLShared:/c/Program Files (x86)/
Common Files/Roxio Shared/OEM/12.0/DLLShared:/c/Program Files (x86)/Roxio/OEM/AudioCore:/c/Program Files/Perforce:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/Skype/Phone:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cmd
:/c/Program Files (x86)/nodejs:/c/Ruby200-x64/bin:/c/tools/php:/c/tools/arcanist/bin:/c/Python27:/c/mongodb/bin:/c/Users/PSWai/AppData/Roaming/npm)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "debug"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! npm-shell-debug@1.0.3 debug: `which sh; echo $SHELL; echo $SHELLOPTS; shopt`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the npm-shell-debug@1.0.3 debug script 'which sh; echo $SHELL; echo $SHELLOPTS; shopt'.
npm ERR! This is most likely a problem with the npm-shell-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     which sh; echo $SHELL; echo $SHELLOPTS; shopt
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-shell-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PSWai\WebstormProjects\pandora\node_modules\npm-shell-debug\npm-debug.log
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm-shell-debug"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! npm-shell-debug@1.0.3 postinstall: `npm run debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-shell-debug@1.0.3 postinstall script 'npm run debug'.
npm ERR! This is most likely a problem with the npm-shell-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run debug
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-shell-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PSWai\WebstormProjects\pandora\npm-debug.log

```

**Comment by exogen** [comment] 2015-11-17 03:27
@pswai Ah, I was hoping to get the Mac output. I'm not sure how to debug the Windows one yet.

**Comment by ianobermiller** [comment] 2015-11-17 03:52
> if it throws an error when lib doesn't exist instead of building, then something's wrong

It should only have to build in `postinstall` if you have a git url in your `package.json`. Our build servers should ensure that it doesn't error out, but they are only testing a few environments.

**Comment by pswai** [comment] 2015-11-17 03:56
@exogen I managed to get a Mac 10.9.5 in my office with Node 5.0.0 (fresh install). I made an empty project to test and surprisingly 0.15.2 installs perfectly!

I have tried with empty project in the Windows machine above and it works like a charm too. I then added local babel, still ok. However, the install fails when `.babelrc` is added.

.babelrc
```json
{
  "presets": ["es2015", "stage-1", "react"]
}
```

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "radium": "0.15.2"
  },
  "devDependencies": {
    "babel-core": "^6.1.20",
    "babel-loader": "^6.1.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-1": "^6.1.18"
  }
}
```

**Comment by exogen** [comment] 2015-11-17 04:35
> It should only have to build in postinstall if you have a git url in your package.json. Our build servers should ensure that it doesn't error out, but they are only testing a few environments.

@ianobermiller Yup! We're currently having this discussion of whether Formidable still wants to support this use case [over here](https://github.com/FormidableLabs/formidable-react-component-boilerplate/issues/56#issue-117068961). I'm just saying that if we're keeping `postinstall` around, then it should actually do its intended job. :)

**Comment by exogen** [comment] 2015-11-17 04:48
@pswai Thanks a ton!

As far as I understand, the problem is that when we ditched `.npmignore`, we didn't add enough files back in our `package.json` `files`. Since `.babelrc` isn't in our npm package anymore, Babel is going to walk up the directory tree in search of a potential `.babelrc` – and in this case, it finds the root package's (the one trying to install Radium).

@ianobermiller I think we should play it safe and include more in `files`, like all the `.rc`-ish files and probably the webpack/Karma stuff, too – we don't know that just because someone is fetching the NPM package, they aren't intending to at some point install dev dependencies and run those tasks. In the case where they need to run `postinstall`, they're at least building and so need any build-related files.

**Comment by marudor** [comment] 2015-11-17 08:51
Can confirm, 0.15.3 installs correctly

**Comment by exogen** [comment] 2015-11-17 10:00
Still testing this... things aren't looking good for building in `postinstall` – but it's entirely Babel's fault. I could use some help wrangling what seems to be crazy Babel behavior.

It turns out that finding a `.babelrc` doesn't stop Babel from traversing upwards in search of more `.babelrc` files to merge – so I don't think adding it to `files` would help.

Our `postinstall` was broken even before `0.15.2`, for `git` installs from a package that had its own `.babelrc` with conflicting options:

```sh
npm install FormidableLabs/radium#v0.15.1
```

...will break in such a scenario. I think we've just gotten lucky so far that there have been no conflicts – but it should obviously be possible to have a `babel@5` project build itself when being installed from a project using `babel@6`.

Things I tried:

1. Using `babel --babelrc` to explicitly specify the config. This didn't stop it from *still* traversing upwards looking for more configs to merge.
2. Specifying `babelrc: false` in our `.babelrc`. The (sparse) docs claim this makes it not look for any more configs... but it appeared to do nothing.
3. Putting a `babel` config section in `package.json`. (Also, having *that* specify `babelrc: false`.)

Nothing stopped Babel from finding the incompatible `.babelrc`. Maybe someone else will have better luck. To me it's looking like doing `postinstall` builds (to support `git` installs) is broken with Babel's config behavior, and about to start visibly blowing up as people transition to `babel@6`.

**Comment by pswai** [comment] 2015-11-17 11:25
@exogen It seems like `babel` config loading mechanism is broken with https://github.com/babel/babel/pull/2695. The PR itself is good but conflict was not resolved properly

**Comment by ianobermiller** [comment] 2015-11-18 04:44
Yeah, this is definitely a bug in babel. I'm all for ditching the postinstall hook if we can come up with a better solution.

**Comment by exogen** [comment] 2015-11-18 17:34
@ianobermiller Yeah...we've had a bunch of discussion around ditching it at Formidable already – it's likely that we'll just end up not supporting `git` installs anymore, and use the more common method of building in `version` or `prepublish`. If we don't build in `postinstall`, then to support `git` we'd need to check `lib` into the repo on any change, which we don't wanna do.

Babel 6 seems to handle `babelrc` in a more sane way, so we could migrate to that. In my mind, the path of *least* resistance is probably to create a simple custom `run-babel.js` script which uses Babel's Node API instead of the CLI – we could almost certainly force it to use a certain set of options then, instead of this crazy `babelrc` bit. Then we could run that instead of `babel`, stay on Babel 5, keep `postinstall`, etc.

The more involved but more forward-looking approach would be to upgrade to Babel 6.

**Comment by ianobermiller** [comment] 2015-11-18 18:21
I'd much rather migrate to Babel 6 than have some kind of script. I was planning to do it at some point already.

**Comment by ianobermiller** [comment] 2015-11-18 18:22
Closing this, if we want to make changes to `postinstall` we can track that separately.

**Closed by ianobermiller** 2015-11-18 18:22 UTC
