### ISSUE TITLE
Multiple Radium bugs/issues

### ISSUE THREAD

**Issue by niksajanjic** [FormidableLabs/radium#817] opened 2016-08-18 19:45 UTC
I don't want to create 4 different issues for bugs/problems that I have with Radium, instead, I created Github repository that explains issues with short GIFs, code examples, and textual explanation. Please open issue for each bug separately if needed and keep track of it there as I also had the problem how to define a name of certain bugs. Here's the repo with full explanation on each bug:

https://github.com/EastCoastProduct/Radium-bugs

**Comment by cbravo** [comment] 2016-09-08 15:48
I am experiencing similar problems around :hover and making sure it is correctly applied at the right times. 

My issue is that I have a <button> element that is disabled (until the form is correctly filled out)  but it seems when you hover over a disabled button the hover state changes but the hover styles are not applied and then when you move your cursor OFF the disabled button the hover state is not updated causing the button to stay "hovered"  and then when the button becomes enabled the hover styles are then applied even if the cursor is not on the button.

**Comment by cbravo** [comment] 2016-09-08 16:10
ahh I see that my issue has been mentioned here [#778](https://github.com/FormidableLabs/radium/issues/778)

**Comment by niksajanjic** [comment] 2016-09-09 10:52
@cbravo I had similar issue with buttons in form where they would be disabled until form is valid and :hover styles would apply even when button is disabled, I also reported that bug along few other people but that seemed to be fixed when I downloaded Radium version 0.18.0.  I can propose you to try latest release if you didn't do that already.

**Comment by niksajanjic** [comment] 2016-09-09 19:07
Also, I'm very unhappy with Radium and the fact that it can't even support the most basic use cases and even when someone reports the obvious issue it takes weeks before they even respond to the issue which is why we're moving away from it. I'll give it a try to new module next project, it still preserves advantages that inline styles offer but it is dynamically transforming actual inline style to true CSS which sounds better solution:

https://github.com/Khan/aphrodite

Not recommending it as I personally don't have enough experience with it, but Radium is no longer working for us.Also, I'm very unhappy with Radium and the fact that it can't even support the most basic use cases and even when someone reports the obvious issue it takes weeks before they even respond to the issue which is why we're moving away from it. I'll give it a try to new module next project, it still preserves advantages that inline styles offer but it is dynamically transforming actual inline style to true CSS which sounds better solution:

https://github.com/Khan/aphrodite

Not recommending it as I personally don't have enough experience with it, but Radium is no longer working for us.

**Comment by alexlande** [comment] 2016-09-09 19:16
Hey @niksajanjic, sorry you had a bad experience and that we let you down. Aphrodite is a great project, I heartily recommend it. 👍

**Comment by faalsh** [comment] 2016-10-14 15:41
I have the same hover issue where hover state doesn't change

https://jsfiddle.net/tm8xsgkx/3/

the above code snippet explain my use case. I'm wondering if there is any plan to fix this or is it by design. Any suggestion??

**Comment by bgeihsgt** [comment] 2017-03-22 20:37
Any updates on this? I'm hitting this too.

**Comment by alexlande** [comment] 2017-09-16 18:28
Closing this as we have other tickets for these issues:

- `:hover`: https://github.com/FormidableLabs/radium/issues/778
- `IndexLink`: https://github.com/FormidableLabs/radium/issues/829
- Placeholder and Clearfix: https://github.com/FormidableLabs/radium/issues/510

**Closed by alexlande** 2017-09-16 18:28 UTC
