### ISSUE TITLE
Does radium support ':require' ':valide', ':in-range' selector ?

### ISSUE THREAD

**Issue by tychota** [FormidableLabs/radium#343] opened 2015-09-05 22:48 UTC
I'm trying to do some html5 validation using radium:

```js
class MetaField extends Component {
  style = {
    base: {
      padding: '0.5em 0.6em',
      display: 'inline-block',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#ccc',
      boxShadow: 'inset 0 1px 3px #ddd',
      borderRadius: '4px',
      verticalAlign: 'middle',
      boxSizing: 'border-box',
      ':focus': {
        outline: 0,
        borderColor: color.primary.main
      },
      ':required': {
        background: color.info.veryLight,
        borderWidth: '1px',
        borderColor: color.info.main
      },
      ':optional': {
        borderWidth: '1px',
        borderStyle: 'dotted'
      },
      ':focus:invalid': {
        background: color.warn.veryLight,
        color: color.warn.main,
        borderColor: color.warn.dark
      },
      ':focus:out-of-range': {
        background: color.warn.veryLight,
        color: color.warn.main,
        borderColor: color.warn.dark
      },
      ':required:invalid': {
        background: color.warn.veryLight,
        color: color.warn.main,
        borderColor: color.warn.dark
      },
      ':required:out-of-range': {
        background: color.warn.veryLight,
        color: color.warn.main,
        borderColor: color.warn.dark
      },
      ':focus:valid': {
        background: color.success.veryLight,
        color: color.success.main,
        borderColor: color.success.dark
      },
      ':focus:in-range': {
        background: color.success.veryLight,
        color: color.success.main,
        borderColor: color.success.dark
      },
      ':required:valid': {
        background: color.success.veryLight,
        color: color.success.main,
        borderColor: color.success.dark
      },
      ':required:in-range': {
        background: color.success.veryLight,
        color: color.success.main,
        borderColor: color.success.dark
      }
    },
    allButSelect: {
      ':focus': {
        'zIndex': 3
      },
      ':first-child': {
        top: '1px',
        borderRadius: '4px 4px 0 0',
        margin: 0
      },
      ':first-child:last-child': {
        top: '1px',
        borderRadius: '4px',
        margin: 0
      },
      ':last-child': {
        top: '-2px',
        borderRadius: '0 0 4px 4px',
        margin: 0
      }
    },
    disabled: {
      cursor: 'not-allowed',
      backgroundColor: '#eaeded',
      color: '#cad2d3'
    },
    readOnly: {
      backgroundColor: '#eee',
      color: '#777',
      borderColor: '#ccc'
    }
  };

  render() {
...
```

But The selector don't seem's to work, apart from focus or hover (which works as expected)

**Comment by tychota** [comment] 2015-09-05 22:50
Surely related to #333

**Comment by alexlande** [comment] 2015-09-07 02:35
@tychota: Yep, these issues are effectively the same as #333. I'm going to close this ticket as a duplicate of that one.

**Closed by alexlande** 2015-09-07 02:35 UTC
