### ISSUE TITLE
Radium incompatible with React ref forwarding

### ISSUE THREAD

**Issue by mmarcuccio** [FormidableLabs/radium#1010] opened 2018-10-20 03:04 UTC
Any component which uses [React ref forwarding](https://reactjs.org/docs/forwarding-refs.html) fails to render when wrapped in the Radium higher order component.

I have created a [minimal reproduction of this issue](https://github.com/mmarcuccio/radium-forward-ref-issue).

Relevant code from repro:
```js
// This works
const TestRadium = Radium(props => <div>Radium works</div>);

// This works
const TestForwardRefs = React.forwardRef((props, ref) => (
  <div ref={ref}>Forward refs work</div>
));

// This does not render
const TestBoth = Radium(TestForwardRefs);
```

**Comment by mmarcuccio** [comment] 2018-10-20 21:09
I have [added unit tests](https://github.com/FormidableLabs/radium/compare/master...mmarcuccio:master) for this issue.

**Comment by kylecesmat** [comment] 2018-10-24 03:30
Thank you so much for providing a reproduction w/ a unit test! Makes traversing the issue much easier. I'll pull it down and investigate.

**Comment by mmarcuccio** [comment] 2018-11-07 22:52
It looks like react-redux also had an [issue with forward refs](https://github.com/reduxjs/react-redux/issues/914) with their `connect` HoC.  I'm not sure if this issue is related, but if it is then it could potentially be useful to learn from their [solution](https://github.com/reduxjs/react-redux/pull/1062).

**Comment by blainekasten** [comment] 2018-12-06 17:32
@mmarcuccio I spent _a lot_ of time trying to find ways to make this work. Unfortunately, do to the way Radium works, I currently believe we will never be able to support this flow. A good note is we can always support the ref being forwarded onto the Radium component like this:

```js
const Comp = Radium(class extends Component {
  render() {
    return <div id={1} ref={this.props.forwardedRef} />;
  }
}

const Wrapped = React.forwardRef((props, ref) => (
  <Comp {...props} forwardedRef={ref} />
));
```

The reason we can't support Radium wrapping a forwardedRef is because Radium highjacks the render cycle, scans the children, and applies styles as necessary. The `forwardRef` returns a special React implementation of an object like this:

```js
{
  $$typeof: Symbol('react.ref'),
  render: function()
}
```

It's not a typical class, or function, and makes it seemingly impossible to get the contents of it's grandchildren. So at this time, I believe the suggested way for Radium is to just use the above flow. If you have any other ideas, thoughts or questions let me know. But at this time I'm going to close this ticket as can't do.

**Closed by blainekasten** 2018-12-06 17:32 UTC
Labels: bug, verified

**Comment by mmarcuccio** [comment] 2018-12-06 19:56
@blainekasten that makes sense, thank you for investigating!
