### ISSUE TITLE
`:active` style stays active when it should not

### ISSUE THREAD

**Issue by menelaos** [FormidableLabs/radium#347] opened 2015-09-10 16:34 UTC
Steps to reproduce:

* Go to http://projects.formidablelabs.com/radium/
* Press mouse button on the radium button
* Move cursor outside of the element
* Release mouse button

Result: The button will stay `:active`.  With pure CSS it does not.

**Comment by ianobermiller** [comment] 2015-09-10 17:17
This looks like a problem with the project website. This doesn't repro on my sites using Radium or in the examples (`npm run examples`). @alexlande, do you know how the project page is using Radium?

**Comment by ianobermiller** [comment] 2015-09-10 17:19
Ah yes, the project page is super out of date: https://github.com/FormidableLabs/radium/tree/gh-pages/js

**Comment by alexlande** [comment] 2015-09-10 17:21
It is out of date, and the example styles don't match up with what's being used in the button, which is not good. I think it's around time that the website was revamped anyway. I can try to take that on.

The bug in question is not a bug though. That's not `:active`, it's `:focus` :volcano:

**Comment by ianobermiller** [comment] 2015-09-10 17:25
Good call, I should have seen that. Thanks @alexlande!

**Comment by menelaos** [comment] 2015-09-10 19:36
I ran into the bug when using the following code (reduced to MWE):

```javascript
import React  from "react";
import Radium from "radium";
import Icon   from "react-geomicons";

const RadiumIcon = Radium(Icon);

const iconStyle =
  { color     : "blue"
  , ":active" : { color : "green" }
  , ":hover"  : { color : "cyan" }
  };

const someIconWithStyle =
  <RadiumIcon name="camera"
              width={64}
              height={64}
              style={iconStyle} />;

const someIconCss =
   <Icon name="camera"
         width={64}
         height={64}
         className="icon" />;

class Example extends React.Component {
  render () {
    return (
      <div>
        <a href="">{someIconWithStyle}</a>
        <a href="">{someIconCss}</a>
      </div>
    );
  }
}
React.render( <Example />
            , document.getElementById("app")
            );
```

The corresponding CSS file

```css
.icon {
  color : blue;
}
.icon:hover {
  color : cyan;
}
.icon:active {
  color : green;
}
```

You can see the effect I described above. I don't really know if that is radium's fault, but since your website showed the same effect, I figured it was you :)

**Comment by ianobermiller** [comment] 2015-10-06 17:17
@menelaos what is the expected effect of the code and what does it actually do? Why would you use Radium *and* a CSS file?

**Comment by menelaos** [comment] 2015-10-06 19:07
The CSS file was only to be able to show the different behaviour side by side. If the problem doesn't occur anymore (cannot test right now), then the problem was probably with react. I vaguely remember there being an issue with mouseenter/mouseleave.

**Comment by ianobermiller** [comment] 2015-12-29 06:37
Closing for now, feel free to reopen if this is still valid.

**Closed by ianobermiller** 2015-12-29 06:37 UTC
Labels: docs

**Comment by Simonify** [comment] 2016-05-02 08:33
I've noticed this happening (it's reproducible on the http://stack.formidable.com/radium/ example) due to the `mouseup` event not being triggered after a drag (`mousemove`).

It appears that calling `event.preventDefault()` in the `mousedown` event handler causes the `mouseup` event to be triggered.
