### ISSUE TITLE
Server-side vendor prefixing?

### ISSUE THREAD

**Issue by erikras** [FormidableLabs/radium#239] opened 2015-07-02 16:52 UTC
Presumably the vendor prefixing is detecting browser version on the client side. This is great and all, but it means that React complains upon client render, since it's rendering something slightly different than the server did.
```
Warning: React attempted to reuse markup in a container but the checksum was invalid.
This generally means that you are using server rendering and the markup generated on
the server was not what the client was expecting. React injected new markup to
compensate which works but you have lost many of the benefits of server rendering.
Instead, figure out why the markup being generated is different on the client or server:
 (client) ient(#dfdfdf, #eee);-webkit-box-shadow:0
 (server) ient(#dfdfdf, #eee);box-shadow:0 2px 6px
```
What's the best way around this? Could a flag be passed to do _all_ vendors or something?

**Comment by erikras** [comment] 2015-07-02 17:03
I just realized that media queries would have the same problem, so this is a fundamental problem with doing inline styles in this way. Unless something in the build process could extract the styles out to a css file, there's no real way around this. Oh well.

**Comment by ianobermiller** [comment] 2015-07-02 17:27
Duplicate of #201.

We can solve prefixing on the server by changing to a useragent based solution. Unfortunately, media queries can only be solved by extracting to CSS.

**Closed by ianobermiller** 2015-07-02 17:27 UTC
