### ISSUE TITLE
Problem using Component.contextTypes

### ISSUE THREAD

**Issue by grossmail1** [FormidableLabs/radium#631] opened 2016-03-17 17:41 UTC
I am using radium in a particular component to perform media queries. I have wrapped my app in a StyleRoot component and everything works out great.  However, when I add the following lines I get an error asking me to add a StyleRoot component to my app.
`Home.contextTypes = {
    router: React.PropTypes.object.isRequired
}`

A little research shows that adding my own router context is somehow overriding the radium context.  Any ideas on how to fix this issue?

Here is my full component

`````` @Radium
class Home extends Component {

    constructor(props, context) {
        super(props, context)

        this.handleLoginSubmit = this.handleLoginSubmit.bind(this)
        this.determineLogin = this.determineLogin.bind(this)
    }
    determineLogin(props) {
        if (props.patronState) {


            if (props.patronState.isLoggedIn) {
                console.log(this.context)
                const { location } = this.props
                const { router } = this.context

                if (location.state && location.state.nextPathname) {
                    router.replace(location.state.nextPathname)
                } else {
                    router.replace('/my/borrowed')
                }

            }
        }

    }

    componentWillMount() {
        this.determineLogin(this.props)
    }

    handleLoginSubmit(login) {
        this.props.login(login.email, login.password)
    }

    render() {

        return (
            <div>
                <div key="one" style={mobile.base}>
                    <MobileHome socialMessages={socialMessages} homeMessages={homeMessages}
                                onLoginSubmit={this.handleLoginSubmit}/>
                </div>
                <div key="two" style={tabletPlus.base}>
                    <FullHome socialMessages={socialMessages} homeMessages={homeMessages}
                              onLoginSubmit={this.handleLoginSubmit}/>
                </div>
            </div>
        )
    }
}
Home.contextTypes = {
    router: React.PropTypes.object.isRequired
}```
``````

**Comment by alexlande** [comment] 2016-03-25 20:35
Hmm, if you could push a minimal reproduction of this issue, it would be helpful.

Not sure without digging into it why `contextTypes` defined on a component would break Radium's `StyleKeeper` context. Ideally, we would merge 

As an immediate (but not great) solution, I would expect that you could resolve this by wrapping your `Home` component in a new component that would get the `router` context and pass it to `Home` as a prop.

**Comment by brendangibson** [comment] 2016-04-12 19:43
I ran into a similar problem, where I had some media queries in a subcomponent that required a <StyleRoot /> wrapper, and also required `router` context.

For testing, I was able to wrap the subcomponent in `ARoot`

```
const ARoot = React.createClass({
			contextTypes: {
				router: React.PropTypes.object
			},
			render: function () {
				return (
					<StyleRoot>
						{this.props.children}
					</StyleRoot>
				);
			}
		});
```

**Comment by matthetherington** [comment] 2016-04-18 15:25
Are you using the Radium decorator?

Just had the same issue and it was because Radium is returning the enhanced class, then I was redefining contextTypes on it.

Calling Radium on the export after defining contextTypes worked for me, for example:

```
class Home extends Component {

    render() {
        ....
    }

}

Home.contextTypes = {
    router: React.PropTypes.object.isRequired
};

export default Radium(Home);
```

Instead of:

```
@Radium
class Home extends Component {

    render() {
        ....
    }

}

Home.contextTypes = {
    router: React.PropTypes.object.isRequired
};

export default Home;
```

**Comment by benjaminjt** [comment] 2016-05-19 06:40
It seems like the solution posted by @matthetherington does work, however, it would be nice if contextTypes could be set using a static get method on the class (as below).

```js
class Component extends React.Component {
  static get contextTypes() {
    return {
      something: React.PropTypes.string,
    };
  }
  render() {
    return <div>{this.context.something}</div>;
  }
}

export default radium(Component);
```

Note: this currently throws the following error (with `radium@0.16.6`):

```
Uncaught TypeError: Cannot set property contextTypes of function RadiumEnhancer() {
      _classCallCheck(this, RadiumEnhancer);
      var _this2 = _possibleConstruct...<omitted>... } which has only a getter
```

**Comment by ianobermiller** [comment] 2016-05-21 05:15
Doesn't this work? If not, it should.

```jsx
class Component extends React.Component {
  static contextTypes = {
    something: React.PropTypes.string,
  };

  render() {
    return <div>{this.context.something}</div>;
  }
}

export default Radium(Component);

**Comment by jtulk** [comment] 2016-07-09 02:05
Is there way to call this out in the docs somewhere as a known complication of the decorator syntax? This is not an easy bug to track down.

**Comment by denis-bergx2** [comment] 2016-12-18 16:31
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import Radium from 'radium';
import styles from '../../css/TopNav';

@connect((({ routing }) => ({ routing })))
class MyComponent extends Component {
  static contextTypes = {
    i18n: React.PropTypes.shape({}),
  }
  render() {

  }
}
MyComponent.propTypes = {
  routing: PropTypes.shape({ }),
};

export default Radium(MyComponent);

Doesn't work at all

**Comment by alexlande** [comment] 2017-09-15 16:41
Closing in favor of #924. Sorry for the trouble here everyone.

**Closed by alexlande** 2017-09-15 16:41 UTC
Labels: docs
