### ISSUE TITLE
React 0.13.x compatibility (without mixins)

### ISSUE THREAD

**Issue by alanrsoares** [FormidableLabs/radium#87] opened 2015-03-13 04:01 UTC
React is deprecating mixins for ES6 classes. So, what would be an alternative to use radium with ES6?

Some inspiration can be found here:
https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775

Any thoughts?

**Comment by ianobermiller** [comment] 2015-03-13 05:41
Nice! I hadn't see that proposal until now. This seems like a decent
alternative, and very similar to my proposal in #80 for Radium.wrap.

**Comment by conradz** [comment] 2015-03-13 13:47
It should be possible to have an implementation that allows you to use it like this:

```js
var React = require('react');
var Radium = require('radium');

var Component = React.createClass({
  render() {
    return <div style={this.props.style} {...this.props.stateEvents}>
      Content
    </div>;
  }
});

var styles = (state, props) => ({
  // can use `state` or `props` here
  margin: '5px',
  states: [ { hover: { margin: '0' } } ]
});

module.exports = Radium.styleResolver(Component, styles);
```

`Radium.styleResolver` would be a higher-order component that would pass the resolved styles as `props.style` and the state event handlers in `props.stateEvents` to the component. `props.stateEvents` would be an object such as `{ onMouseDown: function() { ... } }`. This would get away from mixins and allow using ES6 classes.

The only thing about this that I don't like is that the `styles` function is totally separate from the component class object. We could use a static function to get around this but not sure which would be nicer.

All that said, I think it would be nice to have a release that supports 0.13 without drastically changing the API (still using mixins) in the short term.

**Comment by alexlande** [comment] 2015-03-13 16:49
Thanks all! Release supporting 0.13.x should be ready ~tonight. (There's a matchMedia context issue I want to fix before tagging it, but everything else still works fine if you're using `createClass`.)

**Comment by alexlande** [comment] 2015-03-13 17:54
That said-- going to close this one as a duplicate of #65.

**Closed by alexlande** 2015-03-13 17:54 UTC
Labels: duplicate, enhancement

**Comment by spicydonuts** [comment] 2015-03-16 23:55
A note to anyone who read this and was scared: neither `createClass` or its `mixins` property are depricated.  `0.13` simply allows people to start playing with a class-based style if they don't need mixins and prefer that.

From Facebook's post on `0.13`: "until we have a replacement for current mixin use cases and support for class property initializers in the language, we don't plan to deprecate React.createClass".

It's unfortunate that `createClass` wasn't named `createComponent` or just `component`.  The issue linked by alexlande has some more background.
