### ISSUE TITLE
Help with react router and server rendering

### ISSUE THREAD

**Issue by ondrejbartas** [FormidableLabs/radium#415] opened 2015-11-12 16:47 UTC
Hi guys, i have problem and spent few hours with updating radium from 0.14.3 to 0.15.1. 

I am using as default stack http://github.com/este/este

I could not find a way how to get rid of error on server rendering. I tried to add it by radium to context, i tried to add it manually to context and only thing which was working was to create decorator which takes different context name and passes it as parameter to radium for every component on page :( but it is not nice solution :(

**Comment by Dattaya** [comment] 2015-11-12 19:14
@ondrejbartas have you seen this example that shows how to configure it: https://github.com/FormidableLabs/radium/blob/master/examples/server.js ? There is a bit more details in changelog https://github.com/FormidableLabs/radium/blob/master/CHANGELOG.md

**Comment by isTravis** [comment] 2015-11-12 19:19
I've been following the SSR updates for a couple weeks now - and was stoked when these got pushed last night. I'm having the same problem as @ondrejbartas though. 

Perhaps something with react-router is obscuring the context from being passed down? Confirming that my server-side gets a user-agent from the headers and sticks it into my top-level component with:

**Comment by ondrejbartas** [comment] 2015-11-12 19:20
@Dattaya yes I have seen it and I tried it but with no success.

My guess is that in este is React router which is handling creation of components and passing all data.

Strange thing is that Radium seems to get configuration from context, but when style prefixer comes to play it is completly ignoring these configurations

**Comment by ondrejbartas** [comment] 2015-11-12 19:23
BTW I have tried to add `radiumConfig` into context and without radium all components could access this on server and client. When I added `@Radium` I got error.

**Comment by joshparolin** [comment] 2015-11-12 22:43
Spent a few hours on this problem yesterday to no avail. It seems the React Router team may still be figuring out the best way to implement custom RouterContext which would allow us to pass down / append custom properties from the server.

**Comment by ianobermiller** [comment] 2015-11-13 07:00
Can anyone provide a simple repo that exhibits the problem? That would make this really easy to debug.

**Comment by isTravis** [comment] 2015-11-13 07:18
Not the simplest, but it's a heavily stripped down version of my production setup where I'm hitting the bug.

[https://github.com/isTravis/radiumSSRBugDemo](https://github.com/isTravis/radiumSSRBugDemo)

Originally based off of [https://github.com/erikras/react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example).

**Comment by ondrejbartas** [comment] 2015-11-13 08:51
When I was poking around Radium I think the problem is that RadiumEnhancer is getting valid configuration from context but then resolve styles is not getting that config from context

**Comment by ianobermiller** [comment] 2015-11-16 07:45
I think the problem is that you are passing `component` to `Html`, but then bypassing the rest of React and calling `renderToString` and getting the HTML in a very roundabout way. Maybe I'm missing something, but just rendering `{component}` in the content div makes the error go away and the HTML show up for me in the response.

![image](https://cloud.githubusercontent.com/assets/897931/11176542/f42de45c-8bf2-11e5-81b5-f8880a10fb34.png)

**Comment by ianobermiller** [comment] 2015-11-16 08:15
Also, 0.15.2 removes the error, but adds a warning since prefixing will still not work.

**Comment by isTravis** [comment] 2015-11-16 18:42
Thanks so much @ianobermiller! You're right - it was something funky about my setup. The change you suggested removed the error - and while I needed a few other changes to make all warnings go away, your insight was the key. 

So - I can confirm that SSR vendor-prefixing is working with react router and redux. It *does not* seem to work if I pass radiumConfig directly to <Provider /> or <Router />, but if I have a react component wrapping those two, which does get radiumConfig, that seems to play nicely.

Media queries still don't play nicely - so it's not totally finished yet, but #53 shows that this is known and on the roadmap. (Another option is to put all my media queries in a <Style/> tag, right?)

Thanks for all the help!

**Comment by ianobermiller** [comment] 2015-11-17 03:45
I am working on a solution for media queries, and I have almost completed the code for keyframes, both of which will be compiled to CSS and injected into a root-level style element.

@isTravis, any chance you could write up a little paragraph with code samples on the gotcha of using Radium with other higher-order components that use context, like react router and redux? It would make a nice addition to the docs.

**Comment by mrtnbroder** [comment] 2015-11-27 08:58
Is there a big drawback when I don't wrap `<Provider><RoutingContext {...renderProps}/></Provider` within a radium-fied component but instead, pass the `radiumConfig` directly via `export default radium(radiumConfig)(component)`?

I don't feel like wrapping my provider in another context is a good idea, so I'm looking for a better solution.

**Comment by mrtnbroder** [comment] 2015-11-27 09:18
Actually, the solution was pretty simple.

This is my component: (notice that I *need* to use @radium, so it wraps the component within a radium-component, which is kinda sad?)

```javascript
@radium
class IndexPage extends Component {

  static getDoctype() {
    return '<!doctype html>'
  }

  static renderToStaticMarkup(props) {
    return IndexPage.getDoctype() + renderToStaticMarkup(<IndexPage {...props}/>)
  }

  render() {
    return (
      <html>
       {...}
      </html>
    )
  }
}

export default IndexPage
```

and on the server:

```javascript
function handleRequests(req, res) {
    match({ routes: getRoutes(), location: req.url }, (err, redirect, renderProps) => {
      if (err)
        res.status(500).send(err.message)
      else if (redirect)
        res.status(302).redirect(redirect.pathname + redirect.search)
      else if (renderProps) {
        const radiumConfig = {
          userAgent: req.headers['user-agent']
        }
        const html = renderIndex(renderProps, radiumConfig)
        const err = renderProps.location.error

        res.status(err ? 400 : 200).send(html)
      } else
        res.status(400).send('404')
    })
  }

  function renderIndex(nextProps, radiumConfig) {
    const store = getRootStore()
    const provider = (
      <Provider store={store}>
        <RoutingContext {...nextProps}/>
      </Provider>
    )
    const content = renderToString(provider)
    const html = IndexPage.renderToStaticMarkup({
      content,
      radiumConfig,
      app: DEBUG ? getDevClientApp() : getClientApp()
    })

    return html
  }
```

**Comment by isTravis** [comment] 2015-12-06 13:14
@ianobermiller Sorry for the delay. I don't feel like I have a great grasp of how and why certain higher order components mess with the context needed by Radium (like you said, I think my issue was more one of a funky SSR setup) - so I don't feel confident writing that up for docs quite yet. Let me play with some code samples and try to find the edge cases though and report back.

Also - any update on SSR media queries? Any way I can contribute to that? #397 says they (and keyframes) are close to having a SSR solution. It'll feel like Christmas morning when those land!

**Comment by ianobermiller** [comment] 2015-12-06 22:11
If you'd like to help, please take a look at https://github.com/FormidableLabs/radium/pull/423, which lays the framework for universal CSS (render a style sheet in the root component). In particular, I'd love feedback on the overall mechanism, which you can see by looking at the changes to the example. Namely, you need to add `Radium({isRoot: true})` to your root component.

Also, while I have a branch that uses this same mechanism for media queries, it doesn't support nesting :hover & friends inside media queries, and I'm not sure about the best solution. I'd probably ship universal media queries without nested support as a separate plugin for starters, until I can come up with a better alternative.

**Comment by isTravis** [comment] 2015-12-06 22:41
Great! Looking over the PR now. 

For my (and I would guess many) applications - the two main goals of SSR css are

1. Prevent any initial flicker
2. Ensure that the server-side code is identical to the client-side code (i.e. to prevent errors like the image below).
<img width="1048" alt="screen shot 2015-12-06 at 5 25 41 pm" src="https://cloud.githubusercontent.com/assets/1000455/11616048/e0f289e0-9c3e-11e5-9804-7d635519ca90.png" />

In terms of avoiding flicker - I think the mechanism sounds good. I'm essentially doing the same thing now manually (sticking necessary media queries or keyframes into separate css files that load with the initial html or into a <Style /> component) - so it would be great to have that automated. A simple {root: true} seems straight-forward enough.

Regarding the second issue - of having the server-side code match the client-code - I'm a bit unclear if or how the PR fixes that issue. The server seems to be appending @media: while the client is smart enough not to. Does this new mechanism remove those from the inline styles?

Re: :hover and friends - I'm not too concerned about them being loaded in the SSR. Usually, if my JS hasn't loaded yet, any buttons or divs that have hover actions wouldn't be functional anyways. I probably wouldn't even want to signal a possible action with hover-styling in that case even if I could.

**Comment by alexlande** [comment] 2016-03-28 22:14
Closing this one as I think it's redundant at this pointer.

We have another issue on better documentation for react-router + server-rendering here: https://github.com/FormidableLabs/radium/issues/429

We have another issue on server-rendering-friendly pseudo-selector styles here: https://github.com/FormidableLabs/radium/issues/510

And @ianobermiller landed server-rendering-friendly media queries landed some time ago :boom:

**Closed by alexlande** 2016-03-28 22:14 UTC
Labels: docs
