### ISSUE TITLE
Should be some way to specify the order of Style component media queries

### ISSUE THREAD

**Issue by alexmarchant** [FormidableLabs/radium#720] opened 2016-06-01 22:51 UTC
I'm getting the following css output from the Style component. Working on a mobile-first responsive site, i need a way to say that the 544px comes first...

```css
.class {
  ...
}
@media (min-width: 768px) {
    .class {
      ...
    }
}
@media (min-width: 1200px) {
    .class {
      ...
    }
}
@media (min-width: 544px) {
    .class {
      ...
    }
}
```

**Comment by alexlande** [comment] 2016-06-13 21:02
@alexmarchant: I can't reproduce this issue. Media queries should be applied in the order that they're declared in the `Style` component, just as in normal CSS. There is a separate bug in which generated media queries from inline styles don't have a deterministic order, but that doesn't sound like what you're seeing here.

Could you provide a reproduction of the bug?

**Comment by alexlande** [comment] 2016-07-06 16:34
Going to close this one for now. If you have a repro let me know and we can re-open.

**Closed by alexlande** 2016-07-06 16:34 UTC
Labels: bug, no repro
