### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by jairusd** [FormidableLabs/radium#993] opened 2018-06-26 16:05 UTC
![image](https://user-images.githubusercontent.com/36670564/41924806-875fdc36-799d-11e8-905b-152276a563c9.png)

I have an application running on radium. It's working fine but it doesn't pass jest unit test due to some errors.

**Comment by ryan-roemer** [comment] 2018-06-26 16:07
@jairusd -- Can you create a minimal repository that exhibits the error behavior with installation + error reproduction steps so we can see what you are seeing? Thanks!

**Comment by jairusd** [comment] 2018-06-27 09:41
got a repo here: https://github.com/jairusd/testProject thanks!

**Comment by ryan-roemer** [comment] 2018-07-01 21:30
The problem is that right here: https://github.com/FormidableLabs/radium/blob/master/src/components/style.js#L7

We get:

```js
import PropTypes from 'prop-types';
```

and `PropTypes` is `undefined` (the built `lib` version). Not sure what's up with this, but it might be a jest thing? (I'll keep looking, but this import _should_ work fine).

**Comment by ryan-roemer** [comment] 2018-07-02 22:39
It appears to be an issue with your configuration of Jest `automock` playing poorly with `prop-types`. Apply this diff:

```diff
diff --git a/package.json b/package.json
index 866cd43..2cae5b9 100644
--- a/package.json
+++ b/package.json
@@ -111,7 +111,7 @@
     }
   },
   "jest": {
-    "automock": true,
+    "automock": false,
     "coveragePathIgnorePatterns": [
       "/node_modules/"
     ],
```

and you get:

```sh
$ yarn test
yarn run v1.7.0
$ jest __tests__
 PASS  __tests__/pain/Pain.test.js
  ✓ renders without crashing (17ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        1.058s
Ran all test suites matching /__tests__/i.
✨  Done in 1.97s.
```

So, as it appears to be just Jest + `prop-types` issue (and maybe something with how it's built through a standard babel pipeline), and nothing to do with Radium, I'm closing this issue. Good luck!

**Closed by ryan-roemer** 2018-07-02 22:39 UTC
Labels: unverified
