### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by anirudhaima** [FormidableLabs/radium#961] opened 2018-01-20 08:57 UTC
I am unable to use Radium . whenever i wrap my component in Radium  (Radium(App))  it gives me errors Type Cannot call a class as a function.
Thanx in advance :-)

import React, { Component } from 'react';
**import Radium from 'radium';**
import Person from './Person/Person';
import './App.css';

class App extends Component {.....}
**export default Radium(App);**
Error:
:3000/static/js/bundle.js:41608 Uncaught TypeError: **Cannot call a class as a function**
    at _classCallCheck (:3000/static/js/bundle.js:41608)
    at App (:3000/static/js/bundle.js:41628)
    at RadiumEnhancer.render (:3000/static/js/bundle.js:8669)
    at RadiumEnhancer.render (:3000/static/js/bundle.js:8727)
    at finishClassComponent (:3000/static/js/bundle.js:19690)
    at updateClassComponent (:3000/static/js/bundle.js:19667)
    at beginWork (:3000/static/js/bundle.js:20042)
    at performUnitOfWork (:3000/static/js/bundle.js:22041)
    at workLoop (:3000/static/js/bundle.js:22105)
    at HTMLUnknownElement.callCallback (:3000/static/js/bundle.js:12359)
    at Object.invokeGuardedCallbackDev (:3000/static/js/bundle.js:12398)
    at invokeGuardedCallback (:3000/static/js/bundle.js:12255)
    at renderRoot (:3000/static/js/bundle.js:22183)
    at performWorkOnRoot (:3000/static/js/bundle.js:22831)
    at performWork (:3000/static/js/bundle.js:22784)
    at requestWork (:3000/static/js/bundle.js:22695)
    at scheduleWorkImpl (:3000/static/js/bundle.js:22549)
    at scheduleWork (:3000/static/js/bundle.js:22506)
    at scheduleTopLevelUpdate (:3000/static/js/bundle.js:23010)
    at Object.updateContainer (:3000/static/js/bundle.js:23048)
    at :3000/static/js/bundle.js:27043
    at Object.unbatchedUpdates (:3000/static/js/bundle.js:22919)
    at renderSubtreeIntoContainer (:3000/static/js/bundle.js:27042)
    at Object.render (:3000/static/js/bundle.js:27107)
    at Object../src/index.js (:3000/static/js/bundle.js:41914)
    at __webpack_require__ (:3000/static/js/bundle.js:679)
    at fn (:3000/static/js/bundle.js:89)
    at Object.0 (:3000/static/js/bundle.js:42049)
    at __webpack_require__ (:3000/static/js/bundle.js:679)
    at ./node_modules/ansi-regex/index.js.module.exports (:3000/static/js/bundle.js:725)
    at :3000/static/js/bundle.js:728

**Comment by ryan-roemer** [comment] 2018-01-20 15:03
The example above _should_ work. Can you create a minimal public repository with install + error reproduction steps so we can clone it down and see what you're seeing directly? Thanks!

**Comment by ryan-roemer** [comment] 2018-06-26 16:10
Closing due to lack of reproduction. If you're still experience the issue, please create a minimal public repository with install + error reproduction steps so we can clone it down and see what you're seeing directly and we'll re-open. Thanks!

**Closed by ryan-roemer** 2018-06-26 16:10 UTC
Labels: unverified
