### ISSUE TITLE
Style component outputting object for pseudo-selectors

### ISSUE THREAD

**Issue by oojacoboo** [FormidableLabs/radium#863] opened 2016-12-27 05:16 UTC
I'm trying to figure out why I'm getting an object output from the Style component for the following:

```
    <Style scopeSelector='.floatLabelInput' rules={{
      'input': {
        'backgroundColor': 'hsla(255, 0%, 100%, 0.5)',
        'border': '0',
        ':hover': {
          border: '0',
        },
        ':active': {
          border: '0',
        },
        ':focus': {
          border: '0',
        },
      },
      '::-webkit-input-placeholder': {
        color: placeholderColor,
      },
      ':-moz-placeholder': {
        color: placeholderColor,
      },
      '::-moz-placeholder': {
        color: placeholderColor,
      },
      ':-ms-input-placeholder': {
        color: placeholderColor,
      },
    }} />
```

![image](https://cloud.githubusercontent.com/assets/764664/21491307/b5924392-cbc9-11e6-8bb9-e80a62e7df5f.png)

Thanks.

**Comment by oojacoboo** [comment] 2016-12-27 21:16
I was able to get this working with the following...

```
<Style scopeSelector='.floatLabelInput' rules={{
      'input': {
        backgroundColor: 'hsla(255, 0%, 100%, 0.5)',
        border: '0',
      },
      ':hover': {
        border: '0',
      },
      'input:active': {
        border: '0',
      },
      'input:focus': {
        border: '0',
      },
      'input::-webkit-input-placeholder': {
        color: placeholderColor,
      },
      'input:-moz-placeholder': {
        color: placeholderColor,
      },
      'input::-moz-placeholder': {
        color: placeholderColor,
      },
      'input:-ms-input-placeholder': {
        color: placeholderColor,
      },
    }} />
```

But really... what's the point?  I'm basically just writing css selectors inside of a <style> tag with a way less desirable syntax all to get around the lack of pseudo-selector support.

**Comment by alexlande** [comment] 2017-09-16 18:08
Sorry for the trouble here @oojacoboo. As you noted, the `Style` component doesn't handle nested selectors. Closing this as a duplicate of #712 which is requesting the same feature.

**Closed by alexlande** 2017-09-16 18:08 UTC
