### ISSUE TITLE
Testing Styles

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/radium#72] opened 2015-03-06 14:29 UTC
@ryan-roemer Someone at the last FB meetup brought up that testing styles with Radium is now more feasible "because testing CSS was hell". Any ideas here?

**Comment by ryan-roemer** [comment] 2015-03-06 14:51
@colinmegill -- Should be straightforward to test like we normally do, then run a huge browser matrix with Sauce Labs (maybe with some conditional tests).

**Comment by ryan-roemer** [comment] 2015-03-06 15:05
Closing as duplicate of #70

**Comment by colinmegill** [comment] 2015-03-06 15:08
@ryan-roemer Not a duplicate. Saw that issue, opened this specifically separately - he is asking if we're going to test Radium itself. The person at the meetup was suggesting a story for testing apps that use Radium.

**Comment by colinmegill** [comment] 2015-03-06 15:09
There is at least a blog post here in terms of how the style codebase could now be integrated into the testing story for an app that uses objects instead of CSS

**Comment by ryan-roemer** [comment] 2015-03-06 15:09
Ah! Then definitely re-open.

**Comment by colinmegill** [comment] 2015-03-06 15:10
I didn't really have a great answer for him, but thought it might be a great topic for you!

**Comment by ryan-roemer** [comment] 2015-03-06 15:15
@colinmegill -- Can you explain more what the problem statement is? And what he / others might be looking for? Maybe go track the person down and get more information?

Generally, speaking, testing CSS for class presence / behaviors / visibility isn't so bad with some combination of non-attached, attached-but-hidden and attached-and-visible DOM fixtures. Hypothetically testing via Radium could be slightly easier via object assertions instead of DOM assertions, but just a little.

If we're talking about visual testing / regressions, that will be something more complicated that perhaps @alexlande can do to find the best framework to use.

**Comment by colinmegill** [comment] 2015-03-06 15:27
The former - he was talking about being able to do object assertions now rather than DOM assertions, and he seemed to think that would be much easier. @alexlande?

**Comment by alexlande** [comment] 2015-03-06 18:58
@ryan-roemer: Part of the benefit to CSS testing with Radium (whether you use DOM or object assertions) would be that styles are applied directly to elements, so it's a lot more reliable than checking for the presence of a class or similar. You could verify that an element looks exactly how it should.

With traditional CSS doing this kind of test would involve `getComputedStyles` all over the place, which would work just as well, but it would be pretty convenient with Radium.

**Comment by ianobermiller** [comment] 2015-05-22 17:21
What is the action here? Add something to the documentation about testing components with Radium?

**Comment by alexlande** [comment] 2015-05-24 17:49
I don't think there's anything actionable here. Going to close unless anyone objects.

**Closed by alexlande** 2015-05-24 17:49 UTC
Labels: docs
