### ISSUE TITLE
css vendor prefixing not working

### ISSUE THREAD

**Issue by gutenye** [FormidableLabs/radium#714] opened 2016-05-26 04:35 UTC
I have same issues described here https://github.com/callemall/material-ui/issues/4280

**Comment by kylpo** [comment] 2016-06-10 15:43
@gutenye for me, it was a user-agent issue for server side rendering. Adding this radiumConfig worked for me:

`      
<StyleRoot
        radiumConfig={{userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36'}}
>
  ...
`

**Comment by alexlande** [comment] 2016-06-13 20:38
Closing this as a duplicate of #602. Thanks!

**Closed by alexlande** 2016-06-13 20:38 UTC
