### ISSUE TITLE
[Tracking] 'git clone' + npm@2.15.11 install fails on sinon peerDeps

### ISSUE THREAD

**Issue by MylesBorins** [FormidableLabs/radium#948] opened 2017-12-06 20:32 UTC
Looks to be an issue with peer deps

```
> cd lib || npm run build

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/mborins/.nvm/versions/node/v4.8.6/bin/node" "/Users/mborins/.nvm/versions/node/v4.8.6/bin/npm" "i"
npm ERR! node v4.8.6
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package sinon@1.17.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sinon-chai@2.14.0 wants sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0
npm ERR! peerinvalid Peer karma-sinon-chai@1.3.3 wants sinon@^2.1.0 || ^3.0.0 || ^4.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mborins/code/radium/npm-debug.log
```

**Comment by ryan-roemer** [comment] 2017-12-06 20:39
@MylesBorins -- How are you taking the dependency on `radium`? Or are you trying to `git clone` the project and work on it?

The npm version is rewritten to not even contain `postinstall` -- https://unpkg.com/radium@0.19.6/package.json while the git version does have a `postinstall` -- https://github.com/FormidableLabs/radium/blob/master/package.json#L16 but that shouldn't hit `sinon` as an invalid peer since it's a `devDependencies`.

**Comment by MylesBorins** [comment] 2017-12-06 20:40
git cloning the repo then running `npm install && npm test`

**Comment by ryan-roemer** [comment] 2017-12-06 20:41
OK. I'll take a look at that.

**Comment by ryan-roemer** [comment] 2017-12-06 20:50
What node + npm versions are you on?

It worked for me with:

```
$ node --version && npm --version
v4.8.4
5.5.1
```

Although I did have to run `npm run build` after `npm install` because it didn't run the postinstall command but still exited 0.

Can you try with `yarn`? That's what all the folks on this project use for development of the library itself...

**Comment by MylesBorins** [comment] 2017-12-06 20:51
So we found this when testing with `npm  v2.15.11` the version that comes bundled with `node v4.8.4`

**Comment by ryan-roemer** [comment] 2017-12-06 21:04
Reproduced and verified with:

```
$ node --version && npm --version
v4.8.4
2.15.11
```

Error steps:

```
$ npm install
# ... SNIPPED ...


> radium@0.19.6 postinstall /Users/rye/scm/fmd/radium
> cd lib || npm run build

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/rye/.nvm/versions/node/v4.8.4/bin/node" "/Users/rye/.nvm/versions/node/v4.8.4/bin/npm" "install"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package sinon@1.17.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sinon-chai@2.14.0 wants sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0
npm ERR! peerinvalid Peer karma-sinon-chai@1.3.3 wants sinon@^2.1.0 || ^3.0.0 || ^4.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rye/scm/fmd/radium/npm-debug.log
```

The unfortunate thing here is that supporting ancient npm for `git clone + npm install` is going to be very low priority (as opposed to say to an issue in node4 with an npm dependency). We'll definitely accept a PR that works for everything in our CI matrix with an upgrade, but we're unlikely to take specific action on this issue. Most likely, we'll eventually do a mass dependencies update to everything and it will resolve this issue then.

If you have a specific use case that you need this combination of tools to work with, then perhaps we can help with it. But otherwise, thanks for reporting the issue, and we'll eventually, hopefully get to it! 😄

**Comment by MylesBorins** [comment] 2017-12-06 21:05
Just wanted to let y'all know about this. v4.x is EOL in a couple months so it isn't a priority

**Comment by kylecesmat** [comment] 2018-12-17 01:58
Closing this since v4.x has reached end of life as of 2018-04-30 - https://github.com/nodejs/Release

**Closed by kylecesmat** 2018-12-17 01:58 UTC
Labels: bug, low priority, verified
