### ISSUE TITLE
Wrapping custom function `connect`

### ISSUE THREAD

**Issue by patrickhuang94** [FormidableLabs/radium#878] opened 2017-02-27 19:33 UTC
I'm trying to combine Radium with `connect` from `react-router`. I've taken a look at the Radium docs that suggests wrapping Radium inside a custom component. I tried to do the following:

`import Radium from 'radium'`
`import { connect } from 'react-redux'`
`const Connect = Radium(connect) //as suggested from Radium docs` 

`//render stuff goes here`

`function mapDispatchToProps(dispatch) {`
`    return bindActionCreators(Object.assign({}, {update}), dispatch)`
`}`

`export default Connect(null, mapDispatchToProps)(Radium(App))`
`export { App as AppNoRadium }`

And I'm receiving the error:

> Uncaught TypeError: Cannot call a class as a function

How can I go about this?

**Comment by philipkobernik** [comment] 2017-03-04 01:18
@patrickhuang94 looks a little funky because your Connect is wrapped by Radium, but then you're also wrapping the App component...

FWIW, our team is using this pattern successfully:
```
import Radium from 'radium'
import React from 'react'

class MyComponent extends React.Component {
...
}

export default Radium(Component)
```

in container:
```
import MyComponent from 'MyComponent'
import { connect } from 'react-redux'

const connector = connect(mapStateToProps, mapDispatchToProps)

export default connector(MyComponent)
```

**Comment by mhink** [comment] 2017-04-25 22:26
@patrickhuang94: the above answer is correct.

What you're doing wrong is passing the `connect` function itself to Radium. If you can link me to the page in the docs which suggests this, I'll get it fixed. :) Specifically, here is the errant line:

```javascript
const Connect = Radium(connect); // ???
```

The `Radium` HOC wrapper is meant to be provided with a component- and the trick here is to recognize that such a component may, itself, have already been wrapped. (And this, indeed, is what @philipkobernik is doing, just in two different files.)

```javascript
  const App = () => <p>Hello, world!</p>;
  const ConnectedApp = connect(mapStateToProps, mapDispatchToProps)(Foo);
  const ConnectedAndStyledApp = Radium(ConnectedFoo);
```
See how we're kinda building up the layers of component wrappers? That's the idea here.

Let me know if this helps!

**Comment by ryan-roemer** [comment] 2017-10-17 23:52
Closing, as looks like it's analyzed. If not, feel free to re-open and maybe with a minimal error reproduction repository with install + reproduction steps to help our faster diagnosis and analysis.

Thanks!

**Closed by ryan-roemer** 2017-10-17 23:52 UTC
