### ISSUE TITLE
How to properly support :active on iOS

### ISSUE THREAD

**Issue by 0x80** [FormidableLabs/radium#424] opened 2015-11-17 12:19 UTC
I think this is not specific to Radium but CSS in general, but I'm curious what you propose as a solution. 

If I run the examples on iOS the active pseudoclass sticks when tapping a button. I find answers like [this](http://stackoverflow.com/questions/3885018/active-pseudo-class-doesnt-work-in-mobile-safari) but can't definite official documentation on this. I was hoping you already have a good solution with Radium.

**Comment by ianobermiller** [comment] 2015-11-18 04:41
I haven't thought too much about Radium on mobile. This is a duplicate of #63. If it detects it is on mobile, Radium should use `touchstart` and `touchend` to trigger active states. This would be very easy to add as a plugin. See https://github.com/FormidableLabs/radium/blob/master/src/plugins/resolve-interaction-styles-plugin.js for example.

**Closed by ianobermiller** 2015-11-18 04:41 UTC
Labels: plugin

**Comment by 0x80** [comment] 2015-11-19 10:07
Thanks! :+1:
